// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifF3WLnzLuku4V7rHwv9Mzv-1jqd1j1E',
    appId: '1:208402714657:web:25f40795955c73694d9360',
    messagingSenderId: '208402714657',
    projectId: 'hisseler-658c8',
    authDomain: 'hisseler-658c8.firebaseapp.com',
    storageBucket: 'hisseler-658c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEItcn0OEKaa1MWZ4RCazjWGAfSxueTE',
    appId: '1:208402714657:android:904b21766f5e9c1d4d9360',
    messagingSenderId: '208402714657',
    projectId: 'hisseler-658c8',
    storageBucket: 'hisseler-658c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XZU9HIDTWM1z5IKQBNDjWz2dgt8CRyE',
    appId: '1:208402714657:ios:5ebf0bb8426cf8604d9360',
    messagingSenderId: '208402714657',
    projectId: 'hisseler-658c8',
    storageBucket: 'hisseler-658c8.firebasestorage.app',
    iosBundleId: 'com.example.borsaUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XZU9HIDTWM1z5IKQBNDjWz2dgt8CRyE',
    appId: '1:208402714657:ios:5ebf0bb8426cf8604d9360',
    messagingSenderId: '208402714657',
    projectId: 'hisseler-658c8',
    storageBucket: 'hisseler-658c8.firebasestorage.app',
    iosBundleId: 'com.example.borsaUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifF3WLnzLuku4V7rHwv9Mzv-1jqd1j1E',
    appId: '1:208402714657:web:e6a01369428fc15b4d9360',
    messagingSenderId: '208402714657',
    projectId: 'hisseler-658c8',
    authDomain: 'hisseler-658c8.firebaseapp.com',
    storageBucket: 'hisseler-658c8.firebasestorage.app',
  );
}
